balena-io/deploy-to-balena-action

src/github-utils.ts

I saw in a run where this exception was caught but it did not explain why.

Log error when unable to get checks

---

README.md

Signed-off-by: Chris Crocker-White <chriscw@balena.io>

Minor readme additions

---

events/close-pr/env.example
events/open-pr/env.example
events/push/env.example
events/sync-pr/env.example

Cleanup example env files

---

README.md
action.yml
package-lock.json
package.json
src/action.ts
src/balena-utils.ts
src/github-utils.ts

Use the balena-sdk to get the release `raw_version` after a successful push.
If `create_ref` is true then use octokit to create a ref on the workflow sha.
Resolves: https://github.com/balena-io/balena-ci/issues/17

Optionally add ref to git commit with release version 

---

action.yml

Remove target input from action.yml

---

events/close-pr/env.example
events/open-pr/env.example
events/push/env.example
events/sync-pr/env.example
src/balena-utils.ts

This was causing the push to master workflow to build releases with --draft

Prevent draft on push

---

src/action.ts

Fallback to the current branch sha in case we are pushing to target

---

README.md
src/action.ts

Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>

Adds support for custom source directory as input

---

action.yml
package.json

Correct spec to allow source parameter

---

Dockerfile
src/balena-utils.ts

Previous method did not pass kill signal to CLI correctly which prevented the CLI from telling the builder to stop the build if the action is cancelled.
Closes: #24

24 terminate build

---

src/action.ts

Resolves: #68
Signed-off-by: Tomás Migone <tomas@balena.io>

Do nothing when closing PR without merging

---

action.yml

Name change is required to publish the action to the marketplace

Change name in action.yml to be more unique in marketplace

---

action.yml

Added branding values (icon + color)

---

README.md

Change README heading

---

README.md

Update repo name in README referencing old name

---

README.md
action.yml
events/close-pr/env.example
events/open-pr/env.example
events/push/env.example
events/sync-pr/env.example
src/action.ts
src/github-utils.ts

FD discussion: https://www.flowdock.com/app/rulemotion/pub/threads/DC1_VdFqwIuPiVTUqskgY2OCRDP

Rename create_ref to create_tag as we only ever create tags

---

entrypoint.sh

Exit early if any command in the entrypoint returns non-0 code

---

repo.yml

Resolves: https://github.com/balena-io/deploy-to-balena-action/issues/104

Enable github releases on tagged versions

---

src/balena-utils.ts

Do not log progress bars or empty lines

---

action.yml
src/action.ts
src/balena-utils.ts
src/main.ts
src/types.ts
tests/src/action.spec.ts
tests/src/balena-utils.spec.ts
tests/src/main.spec.ts

Added `layer_cache` input to set `--nocache` flag

---

Dockerfile
package.json

Upgrade to Node 14

---

package-lock.json
package.json

Removed ts-node dev dependency

---

.github/workflows/deploy_release.yml

Build and push action as docker image

---

.github/workflows/deploy_release.yml

Use single quotes on workflow

---

.github/workflows/deploy_release.yml

Correctly detect events to build package

---

src/action.ts
src/balena-utils.ts
tsconfig.json

Resolves: #153
See: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
See: https://www.flowdock.com/app/rulemotion/r-architecture/threads/ghn1N1PeppavnKM2llzOBzUoeSZ
See: https://www.flowdock.com/app/rulemotion/r-product/threads/HQsN094GrNA70eRMgxUISk_QYaw

Add support for working with tag pushes

---

Dockerfile

Bump balena-cli version

---

action.yml
src/action.ts
src/main.ts
src/types.ts

See: https://github.com/balena-io/deploy-to-balena-action/issues/4

Add default branch

---

README.md

I updated the example in the readme to use version v3 for checkout

Update actions/checkout to v3

---

src/action.ts

Supports events from external contributions

Allow pull_request_target event

---

Dockerfile
action.yml

Revert previous

---

action.yml

Mark versionbot as Deprecated in action.yml

---

src/action.ts

Resolves: https://github.com/balena-io/deploy-to-balena-action/issues/193

Set outputs on finalize

---

Dockerfile

Bump balena-cli to 15.1.1

---

.github/actions/publish/action.yml
.github/workflows/flowzone.yml

Move the deploy test action to a custom flowzone test

---

Dockerfile

Update balena CLI to v17.0.0

---

package.json

Update minimum node engine to 16

---

.github/workflows/flowzone.yml

Allow custom actions to run for external contributions

---

package-lock.json

Rebuild package-lock from package.json to fix version drift 

---

versionist.conf.js

We are currently updating package.json and action.yml but that leaves package-lock out-of-sync.

Update package-lock with versionist

---

package-lock.json
package.json

Update to @balena/lint 8.x

---

.github/actions/publish/action.yml

Required since https://github.com/product-os/flowzone/commit/cc152e6aa4a553de8d13342c88c9619fffe93b15

Use the build- prefix to pull draft releases for testing
