src/action.ts
src/balena-utils.ts

This replaces the 2 specific parameters to just being 1 Tags parameter. Makes adding more tags in the future easier rather then add more and more fn params

Refactor getReleaseByTags to require single Tags parameter

---

README.md
action.yml
src/action.ts
src/balena-utils.ts

closes #42 
I didn't think this change would be useful but after having 8/9 runs of this action complete in parallel and the last one failed I had to re run them all...with this change the actions should exit much faster. 
See:

Cache previous builds

---

src/action.ts
src/github-utils.ts

This would always throw an error because the tag would be created on PR open/sync and then on merge we would tag the same commit and fail.

Catch exception if git reference already exists when creating

---

.resinci.yml
package.json

In theory this should also allow bulldozer to auto-merge approved PRs.
See: https://github.com/balena-io/balena-ci/issues/15

Enable npm and docker build tests via balenaCI

---

action.yml
src/action.ts

The action before would error by trying to build in a folder called false as this is the default value for source. This resolves that issue by making the default an empty string. 
```
/usr/bin/balena push balena_os/armv7hf-supervisor --source /github/workspace/false --release-tag balena-ci-commit-sha 526787c3711a3ab3d0c8e31c6ba61a6894e074b8 balena-ci-id 778848383 --draft
Could not access source folder: "/github/workspace/false"
Error: The process '/usr/bin/balena' failed with exit code 1
```

Default source input to empty string instead of false

---

package-lock.json

Otherwise the npm install will fail due to the missing commit.
Resolves: https://github.com/balena-io/balena-ci/issues/66

Update multicast-dns to a new commit since the upstream was rebased

---

src/action.ts

Resolves: https://github.com/balena-io/deploy-to-balena-action/issues/77

Deprecated create_ref doesn't have a default so don't validate boolean

---

entrypoint.sh
src/balena-utils.ts

Not redacting environment provided because in order for you to see the logs you need access to the repo and if you have access to the repo then you'll also be able to see the environment input provided in the workflow.

Pipe CLI whoami test to /dev/null

---

README.md
action.yml
src/action.ts
tests/src/action.spec.ts

Tagging draft releases creates a lot of clutter and references to commits that no longer exist. Instead just tag final releases.

action: Only tag final releases

---

README.md
action.yml
entrypoint.sh

This input is a string representation of a secrets.json file. This means, you do not pass a username and password or token. You instead make your workflow yaml use a [literal scalar](https://yaml.org/spec/1.2-old/spec.html#id2795688) which mimics a secrets.json file. This syntax allows for infinite secrets.json combinations so the action doesn't have to know if you're setting a token vs user/pass or what registry it is for.
The action would therefore look like this:
```
- uses: balena-io/balena-ci@add-registry-auth
name: 'Deploy to miguel/${{ matrix.fleet }}'
id: build
with:
balena_token: ${{ secrets.BALENA_STAGING_TOKEN }} 
environment: balena-staging.com
fleet: 'miguel/${{ matrix.fleet }}' 
registry_secrets: |
{
"ghcr.io": {
"username": "${{ secrets.REGISTRY_USER }}",
"password": "${{ …
```

Added `registry-secrets` input to authenticate with private registries

---

.github/workflows/deploy_release.yml

I noticed the workflow was running on versionbot branches for some reason. This should prevent that.

Only build when event is on master

---

.github/workflows/deploy_release.yml

last setup was causing the meta-data parser action to tag the images as master.. I only wanted version tags.

Build images on tagged commits

---

.github/workflows/deploy_release.yml

old setup would run on tags but because ref was not master it was ignored.

Run image build on base_ref master

---

.github/workflows/deploy_release.yml

I initially added it to avoid unwanted packages being built but you need write permission to the repo.

Don't check author of tag

---

entrypoint.sh

Mitigation for https://github.com/actions/checkout/issues/760 until we can upgrade git to v3.35.2
https://github.blog/2022-04-12-git-security-vulnerability-announced/

Add git WORKDIR as git safe directory

---

README.md

Changed references from `master` branch to `main` in alignment with GitHub's shift to a new default.
GitHub repos now default to `main` instead of `master`. When I created a new repo which had a default branch of `main` and I used the example from the README the workflow didn't trigger because it was pointing to `master`. This change amends the README to refer to the new default, and changes the example action to trigger on both `master` and `main` branches to be backwards compatible. 
See [this article]( https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/#:~:text=Starting%20next%20month,%20all%20new,them%20with%20more%20inclusive%20terms) for changes to GitHub default.

patch: Change `master` branch to `main` in README

---

README.md
action.yml

Versionbot will be deprecated soon. This PR amends the README to avoid users implementing something planned to be removed as part of the phase out. A separate issue has been created to remove it from the code when the time comes. 
https://github.com/balena-io/deploy-to-balena-action/issues/238
https://balena.zulipchat.com/#narrow/stream/345749-loop.2FbalenaLabs/topic/Flowzone/near/319159610

Remove versionbot reference from the README

---

.github/workflows/flowzone.yml

Adds a deploy to Cloud test to run after Flowzone completes.
The test:
- Edits the `action.yml` to tell it to point to the docker image built by Flowzone in the build step before. 
- Overwrites the Dockerfile with a simple busy box image so the test completes quicker than trying to deploy the entire deploy-to-balena Dockerfile just for a deploy test
- Pushes to a test fleet to ensure it works.

Add deployment tests

---

README.md
action.yml
src/action.ts
src/balena-utils.ts
src/main.ts
src/types.ts
tests/src/action.spec.ts
tests/src/balena-utils.spec.ts
tests/src/main.spec.ts

Add multi_dockerignore option

---

README.md
action.yml
src/action.ts
src/balena-utils.ts
src/main.ts
src/types.ts
tests/src/action.spec.ts
tests/src/balena-utils.spec.ts
tests/src/main.spec.ts

This change adds an option to use the `--debug` flag to the Balena push command to allow to see debug build logs.
This PR has been modeled after a similar PR to add the `--multi-dockerignore` flag [here](https://github.com/balena-io/deploy-to-balena-action/pull/249)

Add debug build logs option

---

README.md
action.yml
src/action.ts
src/balena-utils.ts
src/main.ts
src/types.ts
tests/src/action.spec.ts
tests/src/balena-utils.spec.ts
tests/src/main.spec.ts

This change adds an option to use the --debug flag to the Balena push command to allow to see debug build logs.
This PR has been modeled after a similar PR to add the --multi-dockerignore flag [here](https://github.com/balena-io/deploy-to-balena-action/pull/249)

Enable adding a note to the release

---

package.json

This release drops support for Node.js 16, which is EOL after 2023-09-11.
Please upgrade your Node.js to the latest version.
Change-type: major

Drop support for node 16 and npm 8

---

versionist.conf.js

Renovate's lock-file maintenance includes a newline so avoid recursive commits and avoid stripping it.

Append a newline to the package-lock with versionist

---

src/action.ts

This catch was supposed to prevent an abort when the error
was 'Reference already exists' but octokit appends the documentation_url
property to the top level error message field.

Fix catch of reference already exists errors
